import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "@/lib/NextauthProvider";
import { GlobalContextProvider } from "./context/theme";
import { Toaster } from "react-hot-toast";

import localFont from "next/font/local";
// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "../fonts/helvetica/HelveticaNeue-Roman.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <GlobalContextProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </GlobalContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
