import type { Metadata } from "next";
// import { Segoe } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/lib/NextauthProvider";
import { GlobalContextProvider } from "./context/theme";
// const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </GlobalContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
